package uz.mediasolutions.referral.enums;

public enum StepName {
    ENTER_PHONE_NUMBER,
    INCORRECT_PHONE_FORMAT,
    WAITING_APPROVE,
    CHOOSE_FROM_MENU,
    GET_PROMO,
    ENTER_PROMO_CODE,
    CHOOSE_COURSE,
    ENTER_NAME,
    UPLOAD_GIF, CHOOSE_PRIZE, CONFIRM_PRIZE, PENDING_PRIZE_APP, SEND_SCREENSHOT

}
