package uz.mediasolutions.referral.utills.constants;

public interface Message {
    String USERNAME_NOT_FOUND = "username.not.found";
    String MISMATCH_PASSWORDS = "mismatch.passwords";
    String USER_ALREADY_REGISTERED = "user.already.registered";
    String USER_NOT_FOUND_OR_DISABLED = "user.not.found.or.disabled";
    String BAD_REQUEST = "bad.request";

    String ENTER_NAME = "enter.name";
    String ENTER_PHONE_NUMBER = "enter.phone.number";
    String SHARE_PHONE_NUMBER = "share.phone.number";
    String INCORRECT_PHONE_FORMAT = "incorrect.phone.format";
    String MENU_SUG_COMP = "menu.sug.comp";
    String YOU_ARE_BANNED = "you.are.banned";
    String REGISTRATION_MESSAGE = "registration.message";
    String APPROVE = "approve";
    String WELCOME_TO_MENU_STRANGER = "welcome.to.menu.stranger";
    String WELCOME_TO_MENU_STUDENT = "welcome.to.menu.student";
    String GET_PRIVATE_PROMO_CODE = "get.private.promo.code";
    String PRIZES_LIST = "prize.list";
    String MY_BALANCE = "my.balance";
    String USE_PROMO_CODE = "use.promo.code";
    String BACK = "back";
    String PROMO_MESSAGE = "promo.message";
    String ENTER_PROMO_CODE = "enter.promo.code";
    String CHOOSE_COURSE = "choose.course";
    String COURSE_FORMAT = "course.format";
    String CHOSEN_COURSE_MSG = "chosen.course.msg";
    String PAY_CLICK = "pay.click";
    String PAY_PAYME = "pay.payme";
    String WRONG_PROMO_CODE = "wrong.promo.code";
    String NO_ACTIVE_COURSE = "no.active.course";
    String UPLOAD_GIF = "upload.gif";
    String GIF_SAVED = "gif.saved";
    String BALANCE_MSG = "balance.msg";
    String NO_ACTIVE_PRIZES = "no.active.prizes";
    String PRIZE_FORMAT = "prize.format";
    String CONFIRM_PRIZE = "confirm.prize";
    String YES = "yes";
    String NO = "no";
    String APP_RECEIVED = "app.received";
    String PRIZE_APP = "prize.app";
    String NO_PROMO = "no.promo";
    String ACCEPT = "accept";
    String REJECT = "reject";
    String ACCEPT_PRIZE_APP = "accept.prize.app";
    String REJECT_PRIZE_APP = "reject.prize.app";
}
